mols: ['O1C=CN=C1-C']
upperbound_tr: 0
lr_train: 1e-4
use_existent: True

data_preprocess:
  smiles_file: datasets/C.csv

data:
  data_size: 800
  
model:
  num_of_neurons_layer1: 500
  num_of_neurons_layer2: 400
  num_of_neurons_layer3: 300
  #hidden_size: 128
  #num_layers: 2
  #batch_first: True

training:
  num_epochs: 200
  batch_size: 100 #to make it faster you could increase this one (but you can get stuck in local minima)