upperbound_tr: 0.05
lr_train: 1e-4
use_existent: True

data_preprocess:
  smiles_file: datasets/LC50/LC50[-LOG(mol_L)].csv

data:
  data_size: 4800
  
model:
  num_of_neurons_layer1: 750
  num_of_neurons_layer2: 600
  num_of_neurons_layer3: 650
  #hidden_size: 128
  #num_layers: 2
  #batch_first: True

training:
  num_epochs: 20
  batch_size: 50 