mols: ['O1C=CN=C1-C']
upperbound_tr: 0.95 #why random nums to replace zero are not above 0.95?
#consider flipping bits instead
lr_train: 1e-03
use_existent: True

data_preprocess:
  smiles_file: datasets/LC50[-LOG(mol_L)].csv

data:
  data_size: 1000
  
model:
  num_of_neurons_layer1: 50
  num_of_neurons_layer2: 60
  num_of_neurons_layer3: 50

training:
  num_epochs: 8
  batch_size: 1 #to make it faster you could increase this one (but you can get stuck in local minima)