mols: ['O1C=CN=C1-C']
upperbound_tr: 0.95 #why random nums to replace zero are not above 0.95?
#consider flipping bits instead
lr_train: 4e-02
use_existent: True

data_preprocess:
  smiles_file: datasets/C_Count.csv

data:
  data_size: 800
  
model:
  num_of_neurons_layer1: 100
  num_of_neurons_layer2: 100
  num_of_neurons_layer3: 100

training:
  num_epochs: 12
  batch_size: 30 #to make it faster you could increase this one (but you can get stuck in local minima)