mols: ['O1C=CN=C1-C']
upperbound_tr: 0 
lr_train: 1e-03
use_existent: True

data_preprocess:
  smiles_file: datasets/Sol[-LOG(mol_L)].csv

data:
  data_size: 800
  
model:
  num_of_neurons_layer1: 1000
  num_of_neurons_layer2: 750
  num_of_neurons_layer3: 500
  #hidden_size: 128
  #num_layers: 2
  #batch_first: True

training:
  num_epochs: 8
  batch_size: 100 #to make it faster you could increase this one (but you can get stuck in local minima)