mols: ['O1C=CN=C1-C']
upperbound_tr: 0.95 #why random nums to replace zero are not above 0.95?
#consider flipping bits instead
lr_train: 1e-06
test_model: 4

data_preprocess:
  smiles_file: datasets/SelectedSMILES.txt

data:
  num_train: 100
  
model:
  num_of_neurons_layer1: 500
  num_of_neurons_layer2: 500
  num_of_neurons_layer3: 500

training:
  num_epochs: 8
  batch_size: 2 #to make it faster you could increase this one (but you can get stuck in local minima)